---
- name: Update all packages via apt
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400
  when: (ansible_os_family == "Debian")


- name: Upgrade all packages via yum
  yum: name=* state=latest
  when: (ansible_os_family == "RedHat")

- name: Reboot the machine
  shell: "sleep 5 && reboot"

  async: 1
  poll: 0

- name: Wait for the machine to come back online
  wait_for_connection:
    connect_timeout: 60
    sleep: 5
    delay: 5
    timeout: 300
