---

- name: "Ensure apparmor is stopped"
  service:
    name: apparmor
    state: stopped
    enabled: false
  when: (ansible_os_family == "Debian")
  
  tags:
      - security_services
      - selinux
      - apparmor

- block:
  - name: Disable selinux at next reboot
    selinux:
      state: disabled
    ignore_errors: true

  - name: Set selinux in permissive mode until the machine is rebooted
    shell: setenforce 0
    ignore_errors: true

  - name: Change SELINUX /etc/selinux/config
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      state: present
      line: 'SELINUX=disabled'
  when: (ansible_os_family == "RedHat")
  
  tags:
      - security_services
      - selinux
      - apparmor