---

- name: remove other firewalls
  package:
    name: '{{ iptables_packages_removed }}'
    state: absent

- name: install firewall/iptables related packages
  package:
    name: '{{ iptables_packages }}'
    state: present
