---
- name: Ensure awscli-bundle directory does not exist
  file:
    path: '/tmp/awscli-bundle'
    state: absent

- name: Download awscli-bundle.zip
  get_url:
    url: "{{ aws_cli_url }}"
    dest: "/tmp"

- name: Unarchive aws cli from bundle
  unarchive:
    src: '/tmp/awscli-bundle.zip'
    dest: '/tmp'
    remote_src: yes
- name: create symbolik link for python
  file:
    src: '/etc/alternatives/python3' 
    dest: '/usr/bin/python'
    state: link
##  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")

- name: Install aws cli
  shell: '/tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/sbin/aws'

- name: Delete temp folder of aws cli
  file:
    path: '/tmp/awscli-bundle'
    state: absent
