---
# Post tasks

- name: "POST | Find removed but configured apt packages"
  shell: "set -o pipefail;
      dpkg --list | (grep ^rc || true) | tr -s ' ' | cut -d ' ' -f 2"
  args:
      executable: /bin/bash
  register: apt_rc_packages
  changed_when: false

- name: "POST | Perform apt package cleanup"
  apt:
    name: "{{ apt_rc_packages.stdout_lines }}"
    state: absent
    purge: true
  changed_when: false
  ignore_errors: true
  when: not ansible_check_mode
  tags:
    - skip_ansible_lint

- name: "POST | Generate new grub configuration to make sure it's updated due to CIS requirements"
  shell: "set -o pipefail;
      /usr/sbin/update-grub"
  args:
      executable: /bin/bash
  changed_when: false

- name: "Send e-mail notification after CIS settings applied"
  mail:
    timeout: 10
    host: "{{ mailhost }}"
    port: 25
    secure: try
    from: "{{ mailfrom }}"
    to: "{{ mailto }}"
    subject: "CIS settings applied on host: {{ ansible_hostname }}"
    body: |
      Hi team,

      Your server has successfully applied CIS security settings.
      OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      Hostname: {{ ansible_hostname }}
      Host ip: {{ ansible_all_ipv4_addresses }}
           
       --
       Security
  changed_when: false
  ignore_errors: true
  when: mail_notify
