---
- name: "SCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use"
  block:
      - name: "SCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service install"
        apt:
            name: "{{ ubuntu2004cis_time_synchronization }}"
            state: present
            install_recommends: false

      - name: "SCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service start"
        service:
            name: "{{ ubuntu2004cis_time_synchronization }}"
            state: started
            enabled: true

      - name: "SCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service stop ntp"
        service:
            name: "{{ ntp_service[ansible_os_family] }}"
            state: stopped
            enabled: false
        when:
            - ubuntu2004cis_time_synchronization == "chrony"
            - ntpd_service_status.stdout == "loaded"

      - name: "SCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - service stop chrony"
        service:
            name: chronyd
            state: stopped
            enabled: false
        ignore_errors: true
        when:
            - ubuntu2004cis_time_synchronization == "ntp"
            - chronyd_service_status.stdout == "loaded"

      - name: "SCORED | 2.1.1.1 | PATCH | Ensure time synchronization is in use - mask systemd-timesyncd"
        systemd:
          name: systemd-timesyncd
          enabled: no
          masked: yes
        when:
          - ubuntu2004cis_time_synchronization == "ntp"
          - chronyd_service_status.stdout == "loaded"

  when:
      - ubuntu2004cis_rule_2_1_1_1
  tags:
      - level1
      - scored
      - ntp
      - chrony
      - patch
      - rule_2.1.1.1

- name: "SCORED | 2.1.1.2 | PATCH | Ensure systemd-timesyncd is configured"
  lineinfile:
      dest: "{{ timesyncd_config_location }}"
      line: 'NTP= {{ time_synchronization_server_main }}'
      regexp: '(^#)?NTP[\s]*=[\s]*'
      state: present
  notify: restart systemd-timesyncd
  when:
      - ubuntu2004cis_rule_2_1_1_2
      - ubuntu2004cis_time_synchronization == "systemd-timesyncd"
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.1.2
      - timesyncd

- name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured"
  block:
      - name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured | create chrony.conf"
        template:
            src: chrony.conf.j2
            dest: "{{ chrony_config_file[ansible_os_family] }}"
            owner: root
            group: root
            mode: 0644

      - name: "SCORED | 2.1.1.3 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd"
        lineinfile:
            dest: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            state: present
            create: true
  when:
      - ubuntu2004cis_time_synchronization == "chrony"
      - ubuntu2004cis_rule_2_1_1_3
  tags:
      - level1
      - scored
      - chrony
      - patch
      - rule_2.1.1.3

- name: "SCORED | 2.1.1.4 | PATCH | Ensure ntp is configured"
  block:
      - name: "SCORED | 2.1.1.4 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "SCORED | 2.1.1.4 | PATCH | Ensure ntp is configured | modify /etc/init.d/ntp"
        lineinfile:
            dest: /etc/init.d/ntp
            regexp: "^RUNASUSER"
            line: "RUNASUSER=ntp"
  when:
      - ubuntu2004cis_time_synchronization == "ntp"
      - ubuntu2004cis_rule_2_1_1_4
  tags:
      - level1
      - scored
      - ntp
      - patch
      - rule_2.1.1.4

- name: "SCORED | 2.1.2 | PATCH | Ensure X Window System is not installed"
  apt:
      name:
        - "xorg"
        - "x11*"
      state: absent
  when:
      - not ubuntu2004cis_xwindows_required
      - ubuntu2004cis_rule_2_1_2
  tags:
      - level1
      - scored
      - xwindows
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.3 | PATCH | Ensure X Window System is not installed"
  apt:
      name: avahi-daemon
      state: absent
  when:
      - not ubuntu2004cis_avahi_server
      - ubuntu2004cis_rule_2_1_3
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.4 | PATCH | Ensure CUPS is not installed"
  apt:
      name: cups
      state: absent
  when:
      - not ubuntu2004cis_cups_server
      - ubuntu2004cis_rule_2_1_4
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.5 | PATCH | Ensure DHCP Server is not installed - isc-dhcp-server"
  apt:
      name: isc-dhcp-server
      state: absent
  when:
      - not ubuntu2004cis_dhcp_server
      - ubuntu2004cis_rule_2_1_5
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.6 | PATCH | Ensure LDAP server is not installed"
  apt:
      name: slapd
      state: absent
  when:
      - not ubuntu2004cis_ldap_server
      - ubuntu2004cis_rule_2_1_6
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.1.6

- name: "SCORED | 2.1.7 | PATCH | Ensure NFS and RPC are not installed"
  apt:
      name: nfs-kernel-server
      state: absent
  when:
      - not ubuntu2004cis_nfs_rpc_server
      - ubuntu2004cis_rule_2_1_7
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.1.7

- name: "SCORED | 2.1.8 | PATCH | Ensure DNS Server is not installed"
  apt:
      name: named
      state: absent
  when:
      - not ubuntu2004cis_named_server
      - ubuntu2004cis_rule_2_1_8
  tags:
      - level1
      - scored
      - dns
      - services
      - patch
      - rule_2.1.8

- name: "SCORED | 2.1.9 | PATCH | Ensure FTP Server is not installed"
  apt:
      name:
        - "vsftpd"
        - "proftpd"
        - "ftpd"
      state: absent
  when:
      - not ubuntu2004cis_vsftpd_server
      - ubuntu2004cis_rule_2_1_9
  tags:
      - level1
      - scored
      - ftp
      - services
      - patchs
      - rule_2.1.9

- name: "SCORED | 2.1.10 | PATCH | Ensure HTTP server is not installed"
  service:
      name: apache2
      state: stopped
      enabled: false
  when:
      - not ubuntu2004cis_httpd_server
      - httpd_service_status.stdout == "loaded"
      - ubuntu2004cis_rule_2_1_10
  tags:
      - level1
      - scored
      - http
      - services
      - patch
      - rule_2.1.10

- name: "SCORED | 2.1.11 | PATCH | Ensure IMAP and POP3 server is not installed"
  apt:
      name: dovecot
      state: absent
  when:
      - not ubuntu2004cis_dovecot_server
      - ubuntu2004cis_rule_2_1_11
  tags:
      - level1
      - scored
      - imap
      - pop3
      - services
      - patch
      - rule_2.1.11

- name: "SCORED | 2.2.12 | PATCH | Ensure Samba is not installed"
  apt:
      name: samba
      state: absent
  when:
      - not ubuntu2004cis_smb_server
      - ubuntu2004cis_rule_2_1_12
  tags:
      - level1
      - scored
      - samba
      - services
      - patch
      - rule_2.1.12

- name: "SCORED | 2.1.13 | PATCH | Ensure HTTP Proxy Server is not installed"
  apt:
      name: squid
      state: absent
  when:
      - not ubuntu2004cis_squid_server
      - ubuntu2004cis_rule_2_1_13
  tags:
      - level1
      - scored
      - http_proxy
      - services
      - patch
      - rule_2.1.13

- name: "SCORED | 2.1.14 | PATCH | Ensure SNMP Server is not installed"
  apt:
      name: snmpd
      state: absent
  when:
      - not ubuntu2004cis_snmp_server
      - ubuntu2004cis_rule_2_1_14
  tags:
      - level1
      - scored
      - snmp
      - services
      - patch
      - rule_2.1.14

- name: "SCORED | 2.1.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = localhost"
  when:
      - not ubuntu2004cis_is_mail_server
      - postfix_installed.rc == 0
      - ubuntu2004cis_rule_2_1_15
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.15

- name: "SCORED | 2.1.16 | PATCH | Ensure rsync service is disabled"
  systemd:
      name: rsync
      enabled: no
  ignore_errors: yes
  when:
    - not ubuntu2004cis_rsyncd_server
    - ubuntu2004cis_rule_2_1_16
  tags:
    - level1
    - scored
    - rsync
    - services
    - patch
    - rule_2.1.16

- name: "SCORED | 2.1.17 | PATCH | Ensure NIS Server is not installed"
  apt:
      name: nis
      state: absent
  when:
      - not ubuntu2004cis_nis_server
      - ubuntu2004cis_rule_2_1_17
  tags:
      - level1
      - scored
      - nis
      - services
      - patch
      - rule_2.1.17

- name: "SCORED | 2.2.1 | PATCH | Ensure NIS Client is not installed"
  apt:
      name:
        - "yp-tools"
        - "nis"
      state: absent
  when:
      - not ubuntu2004cis_ypbind_required
      - ubuntu2004cis_rule_2_2_1
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.1

- name: "SCORED | 2.2.2 | PATCH | Ensure rsh client is not installed"
  apt:
      name: rsh
      state: absent
  when:
      - not ubuntu2004cis_rsh_required
      - ubuntu2004cis_rule_2_2_2
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.2

- name: "SCORED | 2.2.3 | PATCH | Ensure talk client is not installed"
  apt:
      name: talk
      state: absent
  when:
      - not ubuntu2004cis_talk_required
      - ubuntu2004cis_rule_2_2_3
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.3

- name: "SCORED | 2.2.4 | PATCH | Ensure telnet client is not installed"
  apt:
      name: telnet
      state: absent
  when:
      - not ubuntu2004cis_telnet_required
      - ubuntu2004cis_rule_2_2_4
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.4

- name: "SCORED | 2.2.5 | PATCH | Ensure LDAP client is not installed"
  apt:
      name: ldap-utils
      state: absent
  when:
      - not ubuntu2004cis_openldap_clients_required
      - ubuntu2004cis_rule_2_2_5
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.5

- name: "SCORED | 2.2.6 | PATCH | Ensure RPC is not installed"
  apt:
      name: rpcbind
      state: absent
  when:
      - not ubuntu2004cis_rpc_required
      - ubuntu2004cis_rule_2_2_6
  tags:
      - level1
      - scored
      - patch
      - rule_2.2.6

- name: "NOTSCORED | 2.3 | PATCH | Ensure nonessential services are removed or masked"
  changed_when: false
  debug:
      msg: >
          Run the following command:
          # lsof -i -P -n | grep -v "(ESTABLISHED)"
          Review the output to ensure that all services listed are required on the system. If a listed
          service is not required, remove the package containing the service. If the package
          containing a non-essential service is required, stop and mask the non-essential service.
          Run the following command to remove the package containing the service:
          # apt purge <package_name>
          Run the following command to stop and mask the service:
          # systemctl --now mask <service_name>
  when:
      - not ubuntu2004cis_rpc_required
      - ubuntu2004cis_rule_2_3
  tags:
      - level1
      - notscored
      - patch
      - rule_2.3
