---
- block:
  - name: "Check if dir {{ os_user }}/.ssh exist, create if not"
    file:
      path: "/home/{{ os_user }}/.ssh"
      owner: "{{ os_user }}"
      group: "{{ os_user }}"
      mode: 0700
      state: directory

  - name: Put ssh key in authorized_keys file
    lineinfile:
      path: "/home/{{ os_user }}/.ssh/authorized_keys"
      line: "{{ ssh_key }}"
      owner: "{{ os_user }}"
      group: "{{ os_user }}"
      mode: 0600
      create: yes
      state: present
  when:
      - os_user is defined and ssh_key is defined
  tags:
      - ssh_key
